export default {
    SAVE_STATE: "SAVE_STATE",
    LOAD_STATE: "LOAD_STATE",
    GET_MESSAGES: "GET_MESSAGES",
    GET_MESSAGES_FAIL: "GET_MESSAGES_SUCCESS",
    GET_MESSAGES_SUCCESS: "GET_MESSAGES_SUCCESS",
    ADD_MESSAGE: "ADD_MESSAGE",
    ADD_MESSAGE_FAIL: "ADD_MESSSAGE_FAIL",
    ADD_MESSAGE_SUCCESS: "ADD_MESSAGE_SUCCESS",
    GET_TOKEN: "GET_TOKEN",
    GET_TOKEN_FAIL: "GET_TOKEN_FAIL",
    GET_TOKEN_SUCCESS: "GET_TOKEN_SUCCESS"
}