export default {
    SAVE_STATE: "SAVE_STATE",
    LOAD_STATE: "LOAD_STATE",
    ADD_MESSAGE: "ADD_MESSAGE",
    ADD_MESSAGE_FAIL: "ADD_MESSSAGE_FAIL",
    ADD_MESSAGE_SUCCESS: "ADD_MESSAGE_SUCCESS"
}